on: [push]

name: continuous-integration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout sources
      - uses: actions/setup-node@v2
        name: Setup node 14
        with:
          node-version: '14'
      - uses: actions/setup-python@v1
        name: Setup python 3.8
        with: 
          python-version: "3.8"
      - uses: Gr1N/setup-poetry@v4
        name: Setup poetry tooling
      - run: npm install
        working-directory: client
        name: Install frontend dependencies
      - run: poetry install
        name: Install server dependencies

      - run: npm run lint
        name: Check sources for frontend
        working-directory: client
      - run: npm test
        name: Run unit-tests for frontend
        working-directory: client
      - run: npm run build
        name: Build frontend assets
        working-directory: client

      - run: poetry run flake8 plsexplain
        name: Check sources for server
      - run: poetry run pytest
        name: Run unit-tests for server
      - run: poetry package
        name: Package application

